[package]
name = "projet-pei"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
libc = "0.2.153"
num-integer = "0.1.46"
rand = "0.8.5"
